apiVersion: v2
appVersion: "1.0"
description: Divorce - Case Orchestration Service
name: div-cos
version: 1.5.15
dependencies:
  - name: java
    version: 4.1.5
    repository: https://hmctspublic.azurecr.io/helm/v1/repo/
