apiVersion: v2
appVersion: "1.0"
description: Divorce - Case Orchestration Service
name: div-cos
version: 1.5.9
dependencies:
  - name: java
    version: 3.7.1
    repository: https://hmctspublic.azurecr.io/helm/v1/repo/