java:
  environment:
    APPINSIGHTS_INSTRUMENTATIONKEY: "019ed56f-e01d-4651-895d-bc6334f3d1b1"
    IDAM_API_URL: "https://idam-api.aat.platform.hmcts.net"
    UK_GOV_NOTIFY_API_KEY: "divorce_preprod_live_key-b86e6469-4927-4f50-a029-6ddb523330cf-2409ba37-b5e6-4f03-b052-7d0f0986888d"
    CASE_MAINTENANCE_SERVICE_API_BASEURL: "http://div-cms-aat.service.core-compute-aat.internal"
    IDAM_CITIZEN_USERNAME: "DivCitizenUser@AAT.com"
    PAYMENT_API_BASEURL: "http://payment-api-aat.service.core-compute-aat.internal"
    FEATURE_TOGGLE_SERVICE_API_BASEURL: "http://rpe-feature-toggle-api-aat.service.core-compute-aat.internal"
    SEND_LETTER_SERIVCE_BASEURL: "http://rpe-send-letter-service-aat.service.core-compute-aat.internal"
    IDAM_API_REDIRECT_URL: "https://div-pfe-aat.service.core-compute-aat.internal/authenticated"
    IDAM_CASEWORKER_USERNAME: "DivCaseWorkerUser@AAT.com"
    CASE_FORMATTER_SERVICE_API_BASEURL: "http://div-cfs-aat.service.core-compute-aat.internal"
    SERVICE_AUTH_PROVIDER_URL: "http://rpe-service-auth-provider-aat.service.core-compute-aat.internal"
    CASE_VALIDATION_SERVICE_API_BASEURL: "http://div-vs-aat.service.core-compute-aat.internal"
    IDAM_STRATEGIC_ENABLED: "true"
    DOCUMENT_GENERATOR_SERVICE_API_BASEURL: "http://div-dgs-aat.service.core-compute-aat.internal"
    FEES_AND_PAYMENTS_SERVICE_API_BASEURL: "http://div-fps-aat.service.core-compute-aat.internal"
    MANAGEMENT_ENDPOINT_HEALTH_CACHE_TIMETOLIVE: "30000"

    DIV_SCHEDULER_DB_HOST : ${SERVICE_NAME}-postgresql
    DIV_SCHEDULER_DB_PORT : "5432"
    DIV_SCHEDULER_DB_NAME : div_scheduler
    DIV_SCHEDULER_DB_USER_NAME : div_scheduler_user
    DIV_SCHEDULER_DB_PASSWORD  : div_scheduler_passwd
    FLYWAY_URL : "jdbc:postgresql://${SERVICE_NAME}-postgresql:5432/div_scheduler"
    FLYWAY_USER : div_scheduler_user
    FLYWAY_PASSWORD : div_scheduler_passwd
    SCHEDULER_SCHEDULES_CREATE_BULK_CASES_ENABLED: false
    SCHEDULER_ENABLED: true
  # Don't modify these properties
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}

postgresql:
  postgresqlUsername: div_scheduler_user
  postgresqlPassword: div_scheduler_passwd
  postgresqlDatabase: div_scheduler
  service:
    port: 5432
  persistence:
    enabled: false

