java:
    environment:
        IDAM_API_URL: "https://idam-api.aat.platform.hmcts.net"
        FEATURE_DN_REFUSAL: "true"
        FEATURE_RESP_SOLICITOR_DETAILS: "true"
        SOLICITOR_DN_REJECT_AND_AMEND: "true"
        PAY_BY_ACCOUNT: "true"
        FEATURE_REPRESENTED_RESPONDENT_JOURNEY: "true"
        DATAEXTRACTION_STATUS_DA_EMAILTO: da_data_extraction@sharklasers.com
        DATAEXTRACTION_STATUS_AOS_EMAILTO: aos_data_extraction@sharklasers.com
        DATAEXTRACTION_STATUS_DN_EMAILTO: dn_data_extraction@sharklasers.com
    # Don't modify below here
    image: ${IMAGE_NAME}
    ingressHost: ${SERVICE_FQDN}
    aadIdentityName: divorce
