java:
  environment:
    IDAM_API_URL: "https://idam-api.aat.platform.hmcts.net"
    UK_GOV_NOTIFY_API_KEY: "divorce_preprod_live_key-b86e6469-4927-4f50-a029-6ddb523330cf-2409ba37-b5e6-4f03-b052-7d0f0986888d"
    IDAM_CITIZEN_USERNAME: "DivCitizenUser@AAT.com"
    IDAM_CASEWORKER_USERNAME: "DivCaseWorkerUser@AAT.com"
    MANAGEMENT_ENDPOINT_HEALTH_CACHE_TIMETOLIVE: "30000"
    FEATURE_DN_REFUSAL: "true"

    SCHEDULER_SCHEDULES_CREATE_BULK_CASES_ENABLED: false
    SCHEDULER_ENABLED: true
    FEATURE_RESP_SOLICITOR_DETAILS: "true"

    SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE: false

    DATAEXTRACTION_STATUS_DA_EMAILTO: da_data_extraction@sharklasers.com

  # Don't modify these properties
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}

postgresql:
  enabled: true
  service:
    port: 5432
  persistence:
    enabled: false
