java:
    applicationInsightsInstrumentKey: "686ed071-9c72-4dc3-9edb-191edceb6018"
    environment:
        IDAM_API_URL: "https://idam-api.demo.platform.hmcts.net"
        FEATURE_DN_REFUSAL: "true"
        FEATURE_RESP_SOLICITOR_DETAILS: "true"
        FEATURE_PAPER_UPDATE: true
        SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE: false
        DATAEXTRACTION_STATUS_DA_EMAILTO: da_data_extraction@sharklasers.com
        DATAEXTRACTION_STATUS_AOS_EMAILTO: aos_data_extraction@sharklasers.com
        DATAEXTRACTION_STATUS_DN_EMAILTO: dn_data_extraction@sharklasers.com
    # Don't modify below here
    image: ${IMAGE_NAME}
    ingressHost: ${SERVICE_FQDN}
    aadIdentityName: divorce
