java:
    environment:
        IDAM_API_URL: "https://idam-api.aat.platform.hmcts.net"
        UK_GOV_NOTIFY_API_KEY: "divorce_preprod_live_key-b86e6469-4927-4f50-a029-6ddb523330cf-2409ba37-b5e6-4f03-b052-7d0f0986888d"
        IDAM_CITIZEN_USERNAME: "DivCitizenUser@AAT.com"
        IDAM_CASEWORKER_USERNAME: "DivCaseWorkerUser@AAT.com"
        MANAGEMENT_ENDPOINT_HEALTH_CACHE_TIMETOLIVE: "30000"
        FEATURE_DN_REFUSAL: "true"

        DIV_SCHEDULER_DB_HOST : "div-cos-aat.postgres.database.azure.com"
        DIV_SCHEDULER_DB_PORT : "5432"
        DIV_SCHEDULER_DB_NAME : "div_scheduler"
        DIV_SCHEDULER_DB_USER_NAME : "div_scheduler@div-cos-aat"
        FLYWAY_URL : "jdbc:postgresql://div-cos-aat.postgres.database.azure.com:5432/div_scheduler"
        SCHEDULER_SCHEDULES_CREATE_BULK_CASES_ENABLED: false
        SCHEDULER_RE_CREATE: true
        SCHEDULER_ENABLED: true
        FEATURE_RESP_SOLICITOR_DETAILS: "true"

        SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE: false

        DATAEXTRACTION_STATUS_DA_EMAILTO: da_data_extraction@sharklasers.com

    keyVaults:
        "div":
            resourceGroup: div
            secrets:
                - ccd-submission-s2s-auth-secret
                - div-doc-s2s-auth-secret
                - idam-secret
                - frontend-secret
                - idam-citizen-password
                - idam-caseworker-password
                - cos-postgresql-password

    # Don't modify below here
    image: ${IMAGE_NAME}
    ingressHost: ${SERVICE_FQDN}
    aadIdentityName: divorce
