info:
  app:
    name: ${spring.application.name}

spring:
  application:
    name: div-cos
  resources:
    static-locations:

server:
  port: ${CASE_ORCHESTRATION_SERVICE_URL:4013}

case:
  formatter:
    service:
      api:
        baseurl: ${CASE_FORMATTER_SERVICE_API_BASEURL:http://localhost:4011}
  validation:
    service:
      api:
        baseurl: ${CASE_VALIDATION_SERVICE_API_BASEURL:http://localhost:4008}
  maintenance:
    service:
      api:
        baseurl: ${CASE_MAINTENANCE_SERVICE_API_BASEURL:http://localhost:4010}

idam:
  api:
    url: ${IDAM_API_URL:http://localhost:4503}
    redirect-url: ${IDAM_API_REDIRECT_URL:http://localhost:8080/authenticated}
    port: 4503
    health:
      context-path: /health
  citizen:
    username: dummy
    password: dummy

auth2:
  client:
    id: divorce
    secret: dummy

document:
  generator:
    service:
      api:
        baseurl: ${DOCUMENT_GENERATOR_SERVICE_API_BASEURL:http://localhost:4007}

http:
  connect:
    timeout: 60000
    request:
      timeout: 60000

documentation:
  swagger:
    enabled: true

# GENERAL SPRING BOOT ACTUATOR CONFIG
# Context path for Spring Boot Actuator endpoints
# Allow actuator endpoints to be accessed without requiring authentication
# Enable default health indicators
# Enable disk space health check
management:
  endpoint:
    health:
      show-details: "ALWAYS"
      cache:
        time-to-live: 4000
  endpoints:
    web:
      base-path: /
      path-mapping:
        health: health
      exposure:
        include: info, health, metrics

logging:
  level:
    org.springframework.web: ERROR
    uk.gov.hmcts.reform.divorce.orchestration: DEBUG
  pattern:
    console: "%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n"

azure:
  app_insights_key: ${APPINSIGHTS_INSTRUMENTATIONKEY:false}