info:
  app:
    name: ${spring.application.name}



spring:
  application:
    name: div-cos
  resources:
    static-locations:

server:
  port: ${CASE_ORCHESTRATION_SERVICE_URL:4013}

jackson:
  deserialization:
    ACCEPT_SINGLE_VALUE_AS_ARRAY: true
  serialization:
    FAIL_ON_EMPTY_BEANS: false

case:
  formatter:
    service:
      api:
        baseurl: ${CASE_FORMATTER_SERVICE_API_BASEURL:http://div-cfs-aat.service.core-compute-aat.internal}
  validation:
    service:
      api:
        baseurl: ${CASE_VALIDATION_SERVICE_API_BASEURL:http://div-vs-aat.service.core-compute-aat.internal}
  maintenance:
    service:
      api:
        baseurl: ${CASE_MAINTENANCE_SERVICE_API_BASEURL:http://div-cms-aat.service.core-compute-aat.internal/}

fees-and-payments:
  service:
    api:
      baseurl: ${FEES_AND_PAYMENTS_SERVICE_API_BASEURL:http://div-fps-aat.service.core-compute-aat.internal}

payment:
  service:
    api:
      baseurl: ${PAYMENT_API_BASEURL:http://payment-api-aat.service.core-compute-aat.internal}

feature-toggle:
  service:
    api:
      baseurl: ${FEATURE_TOGGLE_SERVICE_API_BASEURL:http://rpe-feature-toggle-api-aat.service.core-compute-aat.internal}
  toggle:
    bulk-printer-toggle-name: "divorce_bulk_print"
    feature-toggle-520: ${FEATURE_TOGGLE_520:false}

send-letter:
  url: ${SEND_LETTER_SERIVCE_BASEURL:http://rpe-send-letter-service-aat.service.core-compute-aat.internal}

bulk-print:
  dueDate: 30

uk:
  gov:
    notify:
      api:
        key: divorce_preprod_live_key-b86e6469-4927-4f50-a029-6ddb523330cf-2409ba37-b5e6-4f03-b052-7d0f0986888d
      email:
        templates: "{
                      APPLIC_SUBMISSION: 'c323844c-5fb9-4ba4-8290-b84139eb033c',
                      DN_SUBMISSION: 'edf3bce9-f63a-4be0-93a9-d0c80dff7983',
                      GENERIC_UPDATE: '6ee6ec29-5e88-4516-99cb-2edc30256575',
                      RESPONDENT_SUBMISSION_CONSENT: '594dc500-93ca-4f4b-931b-acbf9ee83d25',
                      RESPONDENT_DEFENDED_AOS_SUBMISSION_NOTIFICATION: 'eac41143-b296-4879-ba60-a0ea6f97c757',
                      RESPONDENT_UNDEFENDED_AOS_SUBMISSION_NOTIFICATION: '277fd3f3-2fdb-4c79-9354-1b3db8d44cca',
                      SAVE_DRAFT:'14074c06-87f1-4678-9238-4d71e741eb57'
                    }"
        template:
          vars: "{SAVE_DRAFT: {divorceUrl: 'https://div-pfe-aat.service.core-compute-aat.internal'}}"

courtAllocationConfigurationJson: "
                                  {
                                    \"courtsDesiredWorkloadDistribution\": [
                                      {
                                        \"courtId\": \"eastMidlands\",
                                        \"percentageOfTotalCases\": 0
                                      },
                                      {
                                        \"courtId\": \"southWest\",
                                        \"percentageOfTotalCases\": 0.245
                                      },
                                      {
                                        \"courtId\": \"northWest\",
                                        \"percentageOfTotalCases\": 0.245
                                      },
                                      {
                                        \"courtId\": \"westMidlands\",
                                        \"percentageOfTotalCases\": 0
                                      },
                                      {
                                        \"courtId\": \"serviceCentre\",
                                        \"percentageOfTotalCases\": 0.51
                                      }
                                    ],
                                    \"factSpecificCourtAllocation\": [
                                        {
                                          \"fact\": \"unreasonable-behaviour\",
                                          \"courts\": [
                                            {
                                              \"courtId\": \"serviceCentre\",
                                              \"percentageOfCasesWithThisFactCourtWillHandle\": 1
                                            }
                                          ]
                                        },
                                        {
                                          \"fact\": \"separation-5-years\",
                                          \"courts\": [
                                            {
                                              \"courtId\": \"serviceCentre\",
                                              \"percentageOfCasesWithThisFactCourtWillHandle\": 1
                                            }
                                          ]
                                        }
                                    ]
                                  }"

court:
  details: "{
              \"eastMidlands\":{
                \"divorceCentre\":\"East Midlands Regional Divorce Centre\",
                \"courtCity\":\"Nottingham\",
                \"poBox\":\"PO Box 10447\",
                \"postCode\":\"NG2 9QN\",
                \"openingHours\":\"Telephone Enquiries from: 8.30am to 5pm\",
                \"email\":\"eastmidlandsdivorce@hmcts.gsi.gov.uk\",
                \"phoneNumber\":\"0300 303 0642\",
                \"siteId\":\"AA01\"
              },
              \"westMidlands\":{
                \"divorceCentre\":\"West Midlands Regional Divorce Centre\",
                \"courtCity\":\"Stoke-on-Trent\",
                \"poBox\":\"PO Box 3650\",
                \"postCode\":\"ST4 9NH\",
                \"openingHours\":\"Telephone Enquiries from: 8.30am to 5pm\",
                \"email\":\"westmidlandsdivorce@hmcts.gsi.gov.uk\",
                \"phoneNumber\":\"0300 303 0642\",
                \"siteId\":\"AA02\"
              },
              \"southWest\":{
                \"divorceCentre\":\"South West Regional Divorce Centre\",
                \"courtCity\":\"Southampton\",
                \"poBox\":\"PO Box 1792\",
                \"postCode\":\"SO15 9GG\",
                \"openingHours\":\"Telephone Enquiries from: 8.30am to 5pm\",
                \"email\":\"sw-region-divorce@hmcts.gsi.gov.uk\",
                \"phoneNumber\":\"0300 303 0642\",
                \"siteId\":\"AA03\"
              },
              \"northWest\":{
                \"divorceCentre\":\"North West Regional Divorce Centre\",
                \"divorceCentreAddressName\":\"Liverpool Civil & Family Court\",
                \"courtCity\":\"Liverpool\",
                \"street\":\"35 Vernon Street\",
                \"postCode\":\"L2 2BX\",
                \"openingHours\":\"Telephone Enquiries from: 8.30am to 5pm\",
                \"email\":\"family@liverpool.countycourt.gsi.gov.uk\",
                \"phoneNumber\":\"0300 303 0642\",
                \"siteId\":\"AA04\"
              },
              \"serviceCentre\": {
                \"serviceCentreName\": \"Courts and Tribunals Service Centre\",
                \"divorceCentre\": \"East Midlands Regional Divorce Centre\",
                \"courtCity\": \"Nottingham\",
                \"poBox\": \"PO Box 10447\",
                \"postCode\": \"NG2 9QN\",
                \"openingHours\": \"Telephone Enquiries from: 8.30am to 5pm\",
                \"email\": \"divorcecase@justice.gov.uk\",
                \"phoneNumber\": \"0300 303 0642\",
                \"siteId\": \"AA01\"
              }
           }"

idam:
  api:
    url: ${IDAM_API_URL:https://preprod-idamapi.reform.hmcts.net:3511}
    redirect-url: ${IDAM_API_REDIRECT_URL:https://div-pfe-aat.service.core-compute-aat.internal/authenticated}
    port: 4503
    health:
      context-path: /health
  citizen:
    username: DivCitizenUser@AAT.com
    password: DivPassword1234
  caseworker:
    username: DivCaseWorkerUser@AAT.com
    password: DivPassword1234
  strategic:
    enabled: false
  s2s-auth:
    url: ${SERVICE_AUTH_PROVIDER_URL:http://rpe-service-auth-provider-aat.service.core-compute-aat.internal}
    microservice: ${SERVICE_AUTH_MICROSERVICE:divorce_frontend}
    secret: ${SERVICE_AUTH_SECRET:YTYWFBBMBAQV53AB}

auth2:
  client:
    id: divorce
    secret: thUphEveC2Ekuqedaneh4jEcRuba4t2t

draft:
  api:
    ccd:
      check:
        enabled: ${DRAFT_CCD_CHECK_ENABLED:true}

document:
  generator:
    service:
      api:
        baseurl: ${DOCUMENT_GENERATOR_SERVICE_API_BASEURL:http://div-dgs-aat.service.core-compute-aat.internal}

http:
  connect:
    timeout: 60000
    request:
      timeout: 60000
health:
  check:
    http:
      connect:
        timeout: 5000
        request:
          timeout: 5000

documentation:
  swagger:
    enabled: true

# GENERAL SPRING BOOT ACTUATOR CONFIG
# Context path for Spring Boot Actuator endpoints
# Allow actuator endpoints to be accessed without requiring authentication
# Enable default health indicators
# Enable disk space health check
management:
  endpoint:
    health:
      show-details: "ALWAYS"
      cache:
        time-to-live: 4000
  endpoints:
    web:
      base-path: /
      path-mapping:
        health: health
      exposure:
        include: info, health, metrics

logging:
  level:
    org.springframework.web: ERROR
    uk.gov.hmcts.reform.divorce.orchestration: DEBUG
  pattern:
    console: "%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n"

azure:
  app_insights_key: ${APPINSIGHTS_INSTRUMENTATIONKEY:false}
